pipeline
{
  agent {
  label 'server-1'
  }

  tools {
    maven 'MyMaven-2'
  }

  stages
  {
    stage('Build')
    {
      steps
      {
        sh 'mvn clean package'
      }
      
      post {
        success {
          archiveArtifacts artifacts: '**/target/*.war'
        }
      }
    }
  }
}