pipeline
{
  agent {
  label 'server-1'
  }

  tools {
    maven 'MyMaven-2'
  }

  parameters {
    string(name: 'NAME', defaultValue: 'Neelotpal Chaulia', description: 'Enter your name')
    string(name: 'EMAIL', defaultValue: 'neelchaulia@gmail.com', description: 'Enter your email')
  }

  environment {
    NAME = "Neelotpal Chaulia"
    EMAIL = "neelchaulia@gmail.com"
  }

  stages
  {
    stage('Build')
    {
      steps
      {
        // sh 'mvn clean package'
        echo "Hello, ${params.NAME}. Your email is ${params.EMAIL}"
      }
    }
    
    stage('Test')
    {
      parallel {
        stage('Unit Tests') {
          agent { label 'server-1' }
          steps {
            echo 'Running Unit Tests...'
            // sh 'mvn test -Dtest=UnitTest*'
          }
        }
        stage('Integration Tests') {
          agent { label 'server-1' }
          steps {
            echo 'Running Integration Tests...'
            // sh 'mvn verify -Dtest=IntegrationTest*'
          }
        }
      }
      post {
      success {
          // archiveArtifacts artifacts: '**/target/*.war'
          dir ('simple-java-maven-app') // Apache syntax to change directory
          {
            stash name: 'app', includes: '**/target/*.war'
          }
        } 
      }
    }

    stage('Deploy_development')
    {
      when {
        expression { return params.NAME == 'Neelotpal Chaulia' && params.EMAIL == 'neelchaulia@gmail.com' }
        beforeAgent true // Evaluate condition before allocating agent
        agent { label 'server-1' }
        steps {
          dir ('simple-java-maven-app') {
            unstash 'app'
            echo 'Deploying the application...'
            // sh 'scp target/*.war user@server:/path/to/deploy/'
          }
        }
      }
    }
  }
}
