pipeline
{
  agent {
  label 'server-1'
  }
  stages
  {
    stage('Build')
    {
      steps
      {
        sh 'mvn clean package'
      }
      
      post {
        success {
          archiveArtifacts artifacts: '**/target/*.war'
        }
      }
    }
  }
}